### ISSUE TITLE
Improve underlying css using attr()

### ISSUE THREAD

**Issue by JeremiahSecrist** [Chainlift/liftkit#100]
The [attrs function](https://developer.mozilla.org/en-US/docs/Web/CSS/attr) should be very useful for out project. 
I can already see application to columns and rows in such a fashion that css requires is reduced dramatically. 

### example:
```css
.grid {
  display: grid;
  grid-template-columns: repeat(attr(col type(<number>)), 1fr);
}
```

```html
<div cols="3" class="grid"> 
  <div>hi</div>
  <div>hi</div>
  <div>hi</div>
  <div>hi</div>
  <div>hi</div>
  <div>hi</div>
  <div>hi</div>
</div>
```
